Avoid to serialize values into JSON strings
facile-it/fortepiano pull request #40
Opened 2022-05-23 13:19 UTC by davidecaruso

The `set` method of the **Redis** module always serializes values into JSON strings, regardless the original type of the value. It works for `object` values but, especially for `string` values, produces an unexpected behavior which changes original value (i.e. `foo` --> `"foo"`).

Since Redis only accepts `string` values, keep JSON serialization for `object` value type and cast to `string` the others, returning responsibility of the type-check to the consumers of the client.

2022-05-23 15:59 UTC, xzhavilla commented
> returning responsibility of the type-check to the consumers of the client

Can you elaborate on this?

2022-05-24 07:29 UTC, davidecaruso commented
Yes but we need to change `get` signature to this:

```typescript
export interface Cache {
  readonly get: <A>(
    key: string,
    codec: t.Type<A, J.Json>, // from t.Type<A, unknown>
  ) => TE.TaskEither<Error, A>
  // ...
}
```

If you approve that, I'm going to apply it.

2022-05-24 08:52 UTC, xzhavilla commented
Why shall we?
```typescript
declare const codec: t.Type<{ foo: string }, unknown, unknown>
declare const u: string
const x = JsonFromString.pipe(codec).decode(u)
```

2022-05-25 07:24 UTC, davidecaruso commented
It does not compile, because of the signature of the `encode` function:

`Type 'Encode<{ foo: string; }, unknown>' is not assignable to type 'Encode<{ foo: string; }, Json>'.`

2022-05-25 07:27 UTC, xzhavilla commented
What if we change the signature to something like `Pick<C, 'decode'>` for `get` and `Pick<C, 'encode'>` for `set`?

2022-05-25 07:49 UTC, davidecaruso commented
Do you mean something like that?
```typescript

export interface Cache {
  readonly get: <A, C extends t.Type<A, unknown>>(
    key: string,
    codec: Pick<C, 'name' | 'decode'>,
  ) => TE.TaskEither<Error, A>
  // ...
}
```

2022-05-25 08:32 UTC, xzhavilla commented
Correct, but maybe it's not even needed if you avoid piping codecs and just run them one after the other.

2022-05-25 08:57 UTC, davidecaruso commented
Unfortunately this causes other type errors, because while using it other codec's properties are requested, `decode`/`encode` too, so we can't "pick" them – or if so we need to handle the incompatibilities.

Another quick solution – only for the `get` function – could be the following: 

```typescript
export interface Cache {
  readonly get: <A>(
    key: string,
    codec: t.Type<A, any>,
  ) => TE.TaskEither<Error, A>
  // ...
}
```

It's not too clean but type inference is preserved.

2022-05-25 09:42 UTC, davidecaruso commented
It works! Check it out :smile:

2022-05-25 09:49 UTC, xzhavilla commented
Great! Pet ESLint and don't forget the changelog entry! ;)

2022-05-25 09:50 UTC, xzhavilla requested changes
Great! Pet ESLint and don't forget the changelog entry! ;)

2022-05-25 12:46 UTC, davidecaruso reviewed
It should be ok.

2022-05-25 12:55 UTC, merged