Add http errors
facile-it/fortepiano pull request #53
Opened 2022-10-26 16:22 UTC by pierroberto

See #52

2022-10-26 16:35 UTC, xzhavilla requested changes

2022-10-26 16:35 UTC, xzhavilla commented on src/Http.ts
> +  RequestURITooLong: 414,
Pascal case makes acronyms work as normal words:
```suggestion
  RequestUriTooLong: 414,
```

2022-10-26 16:35 UTC, xzhavilla commented on src/Http.ts
> +  HTTPVersionNotSupported: 505,
Pascal case, again:
```suggestion
  HttpVersionNotSupported: 505,
```

2022-12-20 14:39 UTC, xzhavilla approved these changes

2023-02-20 02:54 UTC, xzhavilla commented
@pierroberto: is this ready to go?

2023-02-20 09:36 UTC, xzhavilla commented
@pierroberto: feel free to merge when ready.

2023-02-20 09:37 UTC, pierroberto commented
@xzhavilla I updated the changelog. It's ready to be merged.

2023-02-20 09:40 UTC, merged