Remove modules
facile-it/fortepiano pull request #88
Opened 2024-10-30 08:41 UTC by pierroberto

Remove the following modules:  `Http`, `Cache`, `Memcached`, `Buffer`, `Stream`, `Memory`, `Redis`, `Storage`, `Axios`, `Fetch`, `Got`, `Flydrive`, `Fs` and their related peer dependencies.

2025-02-18 09:43 UTC, xzhayon approved these changes
Secondo me il modulo `Yield` lo puoi anche rimuovere, mantenere tutto quel codice per una semplicissima ottimizzazione (forse) non merita.

2025-02-18 09:43 UTC, xzhayon commented on package.json
>      "node-fetch": "^2.6.7",
`node-fetch` serve ancora?

2025-02-18 09:43 UTC, xzhayon commented on package.json
>      "@types/node-fetch": "^2.5.12",
`node-fetch` serve ancora?

2025-02-26 17:05 UTC, pierroberto commented on package.json
>      "@types/node-fetch": "^2.5.12",
Credo proprio di no. Rimuovo

2025-02-26 17:12 UTC, xzhayon requested changes

2025-02-26 17:12 UTC, xzhayon commented on src/index.ts
> +    }
Questa cosa non funziona con un array vuoto.

2025-02-26 17:12 UTC, xzhayon commented on src/index.ts
> +    const rndNum = R.randomInt(Math.max(0, min), Math.max(min, max))()
Se `min` e `max` fossero inferiori a zero questa cosa non funzionerebbe bene, ti conviene rimettere `Math.max(0, min, max)` com'era prima.

2025-02-27 09:18 UTC, xzhayon approved these changes

2025-02-27 10:43 UTC, merged